package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FinanceInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("approvedBudget")
	private Double approvedBudget;
	@org.kie.api.definition.type.Label("confirmation")
	private Integer confirmation;

	private java.lang.Double availableBudget;

	public FinanceInformation() {
	}

	public java.lang.Double getApprovedBudget() {
		return this.approvedBudget;
	}

	public void setApprovedBudget(java.lang.Double approvedBudget) {
		this.approvedBudget = approvedBudget;
	}

	public java.lang.Integer getConfirmation() {
		return this.confirmation;
	}

	public void setConfirmation(java.lang.Integer confirmation) {
		this.confirmation = confirmation;
	}

	public java.lang.Double getAvailableBudget() {
		return this.availableBudget;
	}

	public void setAvailableBudget(java.lang.Double availableBudget) {
		this.availableBudget = availableBudget;
	}

	public FinanceInformation(java.lang.Double approvedBudget,
			java.lang.Integer confirmation, java.lang.Double availableBudget) {
		this.approvedBudget = approvedBudget;
		this.confirmation = confirmation;
		this.availableBudget = availableBudget;
	}

}